project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Christophe Ponsard"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Writing
        href: writing/index.qmd
      - text: Support
        href: support/index.qmd
    right:
      - text: "@ChPonsard"
        href: https://x.com/ChPonsard
  page-footer:
    left: "Â© Christophe Ponsard"
    right:
      - text: Contact
        href: mailto:hello@christopheponsard.com

format:
  html:
    theme: cosmo
    toc: true
    link-external-newwindow: true
    smooth-scroll: true
